# environment.yml
name: customer-support-ai
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.1.0
  - torchvision=0.16.0
  - torchaudio=2.1.0
  - cudatoolkit=11.8
  - pandas=2.1.0
  - numpy=1.24.0
  - scikit-learn=1.3.0
  - matplotlib=3.7.0
  - seaborn=0.12.0
  - jupyter=1.0.0
  - pip=23.2.0
  - pip:
    - transformers==4.35.0
    - sentence-transformers==2.2.2
    - langdetect==1.0.9
    - streamlit==1.28.0
    - flask==2.3.0
    - plotly==5.15.0
    - accelerate==0.24.0
    - datasets==2.14.0
    - evaluate==0.4.0
    - nltk==3.8.1
    - tqdm==4.66.0
    - requests==2.31.0
    - scikit-learn-extra  # Alternative to hdbscan